# Generated by Django 5.2.6 on 2025-09-16 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CalculandoIntegrais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcao', models.CharField(max_length=200, verbose_name='Função')),
                ('limite_inferior', models.FloatField(verbose_name='Limite Inferior')),
                ('limite_superior', models.FloatField(verbose_name='Limite Superior')),
                ('resultado', models.FloatField(verbose_name='Resultado')),
                ('numero_retangulos', models.IntegerField(verbose_name='Número de Retângulos')),
                ('erro_estimado', models.FloatField(verbose_name='Erro Estimado')),
                ('data_calculo', models.DateTimeField(auto_now_add=True, verbose_name='Data do Cálculo')),
            ],
            options={
                'verbose_name': 'Cálculo de Integral',
                'verbose_name_plural': 'Cálculos de Integrais',
            },
        ),
    ]
